tinymce.addI18n('supportpal', {
  "Cancel": Lang.get('general.cancel'),
  "Bold": Lang.get('core.bold'),
  "Italic": Lang.get('core.italic'),
  "Underline": Lang.get('core.underline'),
  "Strikethrough": Lang.get('core.strikethrough'),
  "Clear formatting": Lang.get('core.clearformat'),
  "Bullet list": Lang.get('core.unorderedlist'),
  "Numbered list": Lang.get('core.orderedlist'),
  "Decrease indent": Lang.get('core.outdent'),
  "Increase indent": Lang.get('core.indent'),
  "Formats": Lang.get('core.format'),
  "Heading 1": Lang.get('core.heading1'),
  "Heading 2": Lang.get('core.heading2'),
  "Heading 3": Lang.get('core.heading3'),
  "Heading 4": Lang.get('core.heading4'),
  "Heading 5": Lang.get('core.heading5'),
  "Heading 6": Lang.get('core.heading6'),
  "Paragraph": Lang.get('core.paragraph'),
  "Blockquote": Lang.get('core.quote'),
  "Insert\/Edit code sample": Lang.get('core.code'),
  "Insert\/edit link": Lang.get('core.insert_link'),
  "Url": Lang.get('general.url'),
  "Remove link": Lang.get('core.unlink'),
  "Link...": Lang.get('core.edit_link'),
  "Link": Lang.get('core.edit_link'),
  "Open link": Lang.get('core.open_link'),
  "Text color": Lang.get('core.font_color'),
  "Save": Lang.get('general.save'),
  "Color Picker": Lang.get('core.font_color'),
  "Custom Color": Lang.get('core.custom_colour'),
  "Remove Color": Lang.get('core.remove_colour'),
  "Background Color": Lang.get('core.background_colour'),
  "Text to display": Lang.get('general.text'),
  "Open link in...": Lang.get('core.open_link_in'),
  "New window": Lang.get('core.new_window'),
  "Current window": Lang.get('core.current_window'),
  "Image...": Lang.get('core.edit_image'),
  "Insert/edit image": Lang.get('core.insert_image'),
  "Source": Lang.get('general.url'),
  "Alternative description": Lang.get('core.alternative_description'),
  "Upload": Lang.get('core.upload'),
  "General": Lang.get('general.general'),
  "Browse for an image": Lang.get('core.browse_image'),
  "Drop an image here": Lang.get('core.drop_image'),
  "Close": Lang.get('general.close'),
  "Turquoise": Lang.get('core.turquoise'),
  "Green": Lang.get('core.green'),
  "Blue": Lang.get('core.blue'),
  "Purple": Lang.get('core.purple'),
  "Navy Blue": Lang.get('core.navy_blue'),
  "Dark Turquoise": Lang.get('core.dark_turquoise'),
  "Dark Green": Lang.get('core.dark_green'),
  "Medium Blue": Lang.get('core.medium_blue'),
  "Medium Purple": Lang.get('core.medium_purple'),
  "Midnight Blue": Lang.get('core.midnight_blue'),
  "Yellow": Lang.get('core.yellow'),
  "Orange": Lang.get('core.orange'),
  "Red": Lang.get('core.red'),
  "Light Gray": Lang.get('core.light_gray'),
  "Gray": Lang.get('core.gray'),
  "Dark Yellow": Lang.get('core.dark_yellow'),
  "Dark Orange": Lang.get('core.dark_orange'),
  "Dark Red": Lang.get('core.dark_red'),
  "Medium Gray": Lang.get('core.medium_gray'),
  "Dark Gray": Lang.get('core.dark_gray'),
  "Light Green": Lang.get('core.light_green'),
  "Light Yellow": Lang.get('core.light_yellow'),
  "Light Red": Lang.get('core.light_red'),
  "Light Purple": Lang.get('core.light_purple'),
  "Light Blue": Lang.get('core.light_blue'),
  "Dark Purple": Lang.get('core.dark_purple'),
  "Dark Blue": Lang.get('core.dark_blue'),
  "Black": Lang.get('core.black'),
  "White": Lang.get('core.white')
});